# Generated by Django 4.0.2 on 2022-04-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock_tracking_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('prod_description', models.CharField(max_length=100)),
                ('product_code_1', models.IntegerField()),
                ('product_code_2', models.IntegerField()),
            ],
        ),
    ]
