# Generated by Django 4.0.2 on 2022-04-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_tracking_model',
            name='BarCode',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='stock_tracking_model',
            name='Timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stock_tracking_model',
            name='barcode_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
